config/routes.rb
Boxify::Application.routes.draw do
  devise_for :users
  
  resources :warehouses do
    resources :boxes do
      get 'qrCode'
      resources :items
    end  
  end  
  
  resources :categories

   root :to => 'warehouses#index'

end

app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :warehouse
  has_many :items
    
  validates_presence_of :description
  validates_length_of :description, :maximum => 140
  
  searchable do
    text :description, :boost => 5
    text :items do items.map(&:name) + items.map(&:description) end
  end
  
  def create_qr_code(path)
    qrcode = QREncoder.encode(path)
    qrcode.png(:pixels_per_module => 15).save("public/box#{self.id}.png")
  end  
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :box
  belongs_to :category
  
  validates_numericality_of :quantity, 
      :greater_than_or_equal_to =>0, 
      :only_integer => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :warehouses
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :boxes 
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  
  def qrCode
    @box = Box.find(params[:box_id])
    @warehouse = Warehouse.find params[:warehouse_id]
    @box.create_qr_code(warehouse_box_url(@warehouse,@box))
  end  
  
  def show
    @box = Box.find params[:id]
    @warehouse = Warehouse.find params[:warehouse_id]
    @items = @box.items
    @item = Item.new
    render "items/new"
  end  
  
  def new
    @warehouse = Warehouse.find params[:warehouse_id]
    @box = Box.new
    @search = Box.search do
        fulltext params[:search]
      end  
    if params[:search]  
      @boxes = @search.results 
    else
      @boxes = []
    end    
  end
  
  def create
    @warehouse = Warehouse.find params[:warehouse_id]
    @boxes = @warehouse.boxes
    @box = Box.new params[:box]
    @box.warehouse = @warehouse
    if @box.save
      flash[:notice] = "Yey, a box!"
      redirect_to new_warehouse_box_item_path(@warehouse,@box)    
    else
      flash[:error] = "Out of carton..."
      render :new
    end
  end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def new
    @category = Category.new
  end  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def show
    @item = Item.find params[:id]
    @box = Box.find params[:box_id]
    @warehouse = Warehouse.find params[:warehouse_id]
  end  
  
  def new
    @box = Box.find params[:box_id]
    @warehouse = Warehouse.find params[:warehouse_id]
    @items = @box.items
    @item = Item.new 
  end  
  
  def create
    @box = Box.find params[:box_id]
    @warehouse = Warehouse.find params[:warehouse_id]
    @items = @box.items
    @item = Item.create params[:item]
    @item.box = @box
    if @item.save
      flash[:notice] = "Filling the little boxes"
      render :new
    else
      flash[:error] = "Oh noes!"
      render :new
    end    
  end  
  
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  
  def index
    @warehouses = (current_user) ? current_user.warehouses : []
  end  
  
  def new
    @warehouse = Warehouse.new
    @warehouse.user = current_user
    @warehouse.save
    flash[:notice] = "Created Warehouse #{@warehouse.id}"
    redirect_to new_warehouse_box_path(@warehouse)
  end  
  
  def show
    @warehouse = Warehouse.find params[:id]
    @box = Box.new
    @boxes = @warehouse.boxes
    render "boxes/new"
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/boxes/new.html.erb
<% if user_signed_in? %>
  <h2><%= "Warehouse #{@warehouse.id}" %></h2>
  <ul class="boxes-list">
    <% @boxes.each do |box| %>
      <li>
        <span class="box-link"><%= link_to "Box #{box.id}: #{box.description}", warehouse_box_path(@warehouse,box) %></span>
        <span class="qr-link"><%= link_to "Create QR Code", warehouse_box_qrCode_path(@warehouse,box) %></span>
      </li>
    <% end %>
  </ul>
  
  <%= semantic_form_for @box, :url => warehouse_boxes_path(@warehouse) do |f| %>
    <%= f.inputs do %>
      <%= f.input :description %>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button %>
    <% end %>
  <% end %>

  <% content_for :sidebar do %>
    <%= form_tag new_warehouse_box_path(@warehouse), :method => :get do %>
	  <p>
	    <%= text_field_tag :search, params[:search] %>
	    <%= submit_tag "Search", :name => nil %>
	  </p>
	<% end %>
  <% end %>
<% end %>

app/views/boxes/qrCode.html.erb
<div class="box">
  <div class="box-id"><%= @box.id %></div>
  <div class="box-qrcode"><%= image_tag "/box#{@box.id}.png" %></div>
</div>

app/views/categories/new.html.erb
<%= semantic_form_for @category, :url => categories_path do |f| %>
    <%= f.inputs do %>
	  <%= f.input :name %>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button %>
    <% end %>
  <% end %>

app/views/items/new.html.erb
<% if user_signed_in? %>
  <ul class="items-list">
    <% @items.each do |item| %>
      <li><%= link_to "Item #{item.id}: #{item.name}", warehouse_box_item_path(@warehouse, @box, item), :method => :get %></li>
    <% end %>
  </ul>
  
  <%= semantic_form_for @item, :url =>  warehouse_box_items_path(@warehouse,@box) do |f| %>
    <%= f.inputs do %>
	  <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :quantity %>
      <%= f.input :category %>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button %>
    <% end %>
  <% end %>

  <% content_for :sidebar do %>
    <%= link_to "Boxes", warehouse_path(@warehouse) %>
    <%= link_to "Category", new_category_path %>
  <% end %>
<% end %>

app/views/items/show.html.erb
<div class="item">
  <span class="name"><%= @item.name %></span>
  <span class="description"><%= @item.description %></span>
</div>	

<% content_for :sidebar do %>
  <%= link_to "Boxes", warehouse_path(@warehouse) %>
  <%= link_to "Items", warehouse_box_path(@warehouse,@box) %>
  <%= link_to "Category", new_category_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boxify</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.4.1/build/cssreset/cssreset-min.css">
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>

  <body>
    <div id="wrapper">
      <div id="header">
        <span id="product-name">Boxify</span>
  
        <div id="user-management">
          <% if user_signed_in? %>
            <div class="user-name"><%= current_user.email %></div>
            <div class="logout"><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></div>
          <% else %>
            <div class="sign-in"><%= link_to "Sign in", new_user_session_path %></div>
            <div class="sign-up"><%= link_to "Sign up", new_user_registration_path %></div>
          <% end %>
        </div>
      </div>
  
      <div id="content">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= content_tag :h1, yield(:title) if show_title? %>
  
        <div id="main">
          <%= yield %>
        </div>

        <div class="sidebar">
          <%= link_to "Warehouses", warehouses_path if user_signed_in? %>
          <%= yield :sidebar %>
        </div>	
      </div>
    </div>
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/warehouses/index.html.erb
<% if user_signed_in? %>
  <% @warehouses.each do |warehouse| %>
    <%= link_to "Warehouse #{warehouse.id}", warehouse_path(warehouse)  %>
  <% end %>
 
  <%= button_to "Create Warehouse", new_warehouse_path, :method => :get  %>
<% end %>

app/views/warehouses/new.html.erb
<% if user_signed_in? %>
  <h2><%= "Warehouse #{@warehouse.id}" %>
  <%= button_to "Add Box", new_warehouse_box_path(@warehouse), :method => :get  %>
<% end %>